### ISSUE TITLE
Error : [Errno 11002] getaddrinfo failed

### ISSUE THREAD

**Issue by IKDH** [vsakkas/sydney.py#102]
I have this error since today : [Errno 11002] getaddrinfo failed

I use the script with cookies.

**Comment by vsakkas** [comment]
Hi @IKDH Doesn't look like I can reproduce this easily. Does it always happen when you run your script?
Can you share the full traceback?

**Comment by IKDH** [comment]
I don't use proxy. I have tried several network yesterday but today, it's working again. Maybe a problem with Bing Chat in my region ?

**Comment by IKDH** [comment]
By the way, someone updated the EdgeGPT library. It was a very good library in Python but the owner stopped to maintain it. If you want to take a look at the new one : https://github.com/Integration-Automation/ReEdgeGPT

**Comment by vsakkas** [comment]
> I don't use proxy. I have tried several network yesterday but today, it's working again. Maybe a problem with Bing Chat in my region ?

Possibly some hiccup in the service or server that serves your region, but feel free to reopen this issue if it occurs again!
