### ISSUE TITLE
sydney.exceptions.CreateConversationException: Failed to create conversation, received status: 404

### ISSUE THREAD

**Issue by tiernan1979** [vsakkas/sydney.py#105]
Getting this error when using Sydney-Client with Python3.10 and Python3.11 on Ubuntu 22.04.03 and Debian 12
I know the _U cookie is correct so I'm unsure why im getting this error.
Please help. 

Traceback (most recent call last):
  File "/home/xxxx/testing.py", line 24, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/xxxx/testing.py", line 7, in main
    async with SydneyClient(bing_u_cookie="x", style="precise") as sydney:
  File "/usr/local/lib/python3.10/dist-packages/sydney/sydney.py", line 93, in __aenter__
    await self.start_conversation()
  File "/usr/local/lib/python3.10/dist-packages/sydney/sydney.py", line 427, in start_conversation
    raise CreateConversationException(
sydney.exceptions.CreateConversationException: Failed to create conversation, received status: 404
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f494528a320>

**Comment by vsakkas** [comment]
Hi @tiernan1979 I believe I have seen this error before a few times when running the test suite. Does it keep happening even when you rerun your code?

**Comment by tiernan1979** [comment]
Hi Vsakkas, I have just tried again this morning and it appears to be working.. Potentially while trying to automate the login via Selenium they blocked me potentially.
Thanks
Grant

**Comment by vsakkas** [comment]
That seems like a likely cause, Bing servers don't like when we do too many requests at once!
Let me know if this error persists later on, also, automating the login is a cool project to work on :)
