### ISSUE TITLE
Prompt to shorter the response of Bing Chat creative mode

### ISSUE THREAD

**Issue by IKDH** [vsakkas/sydney.py#106]
Hello, I am using Bing Chat creative mode to generate marketing content. I have some trouble to force the AI to shorter the response.
I could use precise mode to do that but I prefer the content generated by the creative mode. Does anyone have found a good prompt to force the AI to writer a certain number of words ?

Thank you !

**Comment by vsakkas** [comment]
@IKDH This is definitely an interesting topic to explore!

I don't know if you have permissions for it, but if you want, feel free to open a discussion on this so other users can find it as well.

But coming back to the topic, I find that using phrases such as `Describe X in about 50 words` or `Write about X in about 100 words` can help guide model a bit.
Also, although this gives you less control, using phrases such as `Be concise` or `Write a short paragraph` can also help.

**Comment by IKDH** [comment]
Thank you. I will make more test and if I find something conclusive, I will share it.
