### ISSUE TITLE
How to use proxy?

### ISSUE THREAD

**Issue by AkiraShiro** [vsakkas/sydney.py#114]
I need to use proxies for use in my area

**Comment by vsakkas** [comment]
Hi @AkiraShiro 
To use proxy, you need to set the following environment variables:
- `HTTPS_PROXY`
- `HTTP_PROXY`
And then, when you create the `SydneyClient`, set the proxy parameter to `True`.

So, for example, if the address of your proxy is `http://127.0.0.1:8080`, this is what you set these environment variables to be.
