### ISSUE TITLE
Stuck on CAPTCHA after update to newest code

### ISSUE THREAD

**Issue by phamxtien** [vsakkas/sydney.py#115]
Before update, just go to bing.com/chat and input 'hi' >> Enter to pass CAPTCHA.
After update, i can not pass CAPTCHA

**Comment by phamxtien** [comment]
Because i only pass _U

**Comment by phamxtien** [comment]
How to get all cookies as string?

**Comment by vsakkas** [comment]
Glad that you figured out the issue @phamxtien !
If you and other uses think it is necessary, I might look into re-adding support for the _U cookie for when the user has not provided the full cookies, although I think the overall behavior should be better when using all the cookies!
That being said, if you think that something was unclear in the updated docs, let me know and I try to improve the instructions

**Comment by phamxtien** [comment]
Thanks @vsakkas, now I updated to newest code

**Comment by phamxtien** [comment]
After update newest code (full cookies) i don't need saying hi to pass CAPTCHA.
Thanks @vsakkas
