### ISSUE TITLE
Disable web access

### ISSUE THREAD

**Issue by gustavosmendes1** [vsakkas/sydney.py#116]
Add option to disable web access or using system prompts. 

The web access is considered as plugin now.

I'm already searching for methods :)

**Comment by gustavosmendes1** [comment]
Actually, just need to add "nosearchall" to options in enums

**Comment by vsakkas** [comment]
H @gustavosmendes1 Do you mean that providing this extra flag disables Bing Chat/Copilot from searching the web?
I will look into it as well and possibly push a release for this in the weekend!

**Comment by gustavosmendes1** [comment]
Exactly.

**Comment by vsakkas** [comment]
Thanks for the investigation! I will have some time later today/tomorrow to implement and do some testing!

**Comment by vsakkas** [comment]
@gustavosmendes1 Latest version has `search` parameter on `ask` method!
