### ISSUE TITLE
I can't use cookie from a non logged session

### ISSUE THREAD

**Issue by IKDH** [vsakkas/sydney.py#126]
Hello, I would like to use this librairy without being connected to my Microstoft account. It is possible with this URL for example : https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx&wlsso=0

But when I try to use the librairy and I add the cookie of this session (it's a cookie without the _U), it triggers a captcha that I can't solve with the non login session (the captcha doesn't appear in the session).

**Comment by vsakkas** [comment]
Closing this one as it seems that `0.20.1` fixed it
