### ISSUE TITLE
 sydney.exceptions.ThrottledRequestException: Request is throttled

### ISSUE THREAD

**Issue by wangjk666** [vsakkas/sydney.py#133]
I installed sydney and have used it for several days. However, recently I always met an error:

"sydney.exceptions.ThrottledRequestException: Request is throttled". I wonder what I should do to fix this. Thanks!

**Comment by vsakkas** [comment]
Hi @wangjk666 

Bing Chat has a limit on the amount of prompts you can send within a day. It seems that you've reached that limit for today.

There are some options here:
- Get new cookies, preferably from a different account.
- Use a proxy or change your IP.
- Wait until tomorrow.

Hope that helps!

**Comment by Mefisto4444** [comment]
@wangjk666 You can replace cookies with new ones to bypass this limit
```python
def prepare_cookies(cookies:RequestsCookieJar):
    """Prepare cookies for sydney"""
    base_str =  json.dumps(dict(cookies.items()))
    return base_str.replace('{','').replace('}','').replace(',',';').replace(': ','=').replace('"','')

def get_new_cookies() -> RequestsCookieJar:
    """Returns new cookies to use in Bing Chat"""
    res = requests.get('https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx')
    return res.cookies

async with SydneyClient(style='Precise', bing_cookies=cookies) as sydney:
    #Your code
    except ThrottledRequestException:
        sydney.bing_cookies = prepare_cookies(get_new_cookies())
```

**Comment by wangjk666** [comment]
Hi @vsakkas @Mefisto4444 Thanks very much for your help. I tried as you suggested but still failed, sydney keeps throwing the above error.

```python
async with SydneyClient(style='Precise', bing_cookies=cookies) as sydney:
        suc = False
        try_times = 5
        
        while not suc and try_times > 0:
            try:
                response = await sydney.ask(this_prompt, attachment=f"https://interndatasetsv2.blob.core.windows.net/omnicaption/cityscapes/cityscapes_som/{img_path}?sv=2019-12-12&st=2023-07-26T13%3A05%3A21Z&se=2024-03-27T13%3A05%3A00Z&sr=c&sp=racwdxlt&sig=MDuvyKPvXoc4WLuds62avH7HXLh6khz1POW%2FAaKl2PQ%3D")
                suc = True
            except ThrottledRequestException:
                sydney.bing_cookies = prepare_cookies(get_new_cookies())
                try_times -= 1
```

**Comment by Mefisto4444** [comment]
@wangjk666 If you can, send session cookies to Sydney without logging in to your Microsoft account.  Check if the browser on your device can use Bing Chat.  If not, it's an IP ban.  You need to use a proxy

**Comment by IKDH** [comment]
The "Request is throttled" message means that your Microsoft account has reached the limit of 300 messages per day. Replacing the cookie won't help. Do the test and go to your Microsoft Copilote UI and try to send a message, you will see.

In order to bypass this, you have to use a different Microsoft account or use Bing Copilote without being connected to your Microsoft account.

**Comment by wangjk666** [comment]
> Request is throttled" message means that your Microsoft account has reached the limit of 300 messages per day. Replacing the cookie won't help.

**Comment by wangjk666** [comment]
I use these functions to get a cookie:

```python

def prepare_cookies(cookies:RequestsCookieJar):
    """Prepare cookies for sydney"""
    base_str =  json.dumps(dict(cookies.items()))
    return base_str.replace('{','').replace('}','').replace(',',';').replace(': ','=').replace('"','')

def get_new_cookies() -> RequestsCookieJar:
    """Returns new cookies to use in Bing Chat"""
    res = requests.get('https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx')
```

I think I don't get access to Copilot with my Microsoft account, right?

**Comment by Mefisto4444** [comment]
No, but if you import cookies from browser where you are logged to Microsoft account and then use these functions then It might cause some troubles

**Comment by vsakkas** [comment]
> No, but if you import cookies from browser where you are logged to Microsoft account and then use these functions then It might cause some troubles

I don't know how true this is in practice, though. I have been developing this library for several months, using my personal account without getting banned. I occasionally get throttled, but that's just part of the development.

That being said, if using the library without cookies if without logging in works, then that's great!

**Comment by wangjk666** [comment]
I agree with you. But if I don't get access to Copilot with my Microsoft account, why I could "reached the limit of 300 messages per day.". I wonder whether it's most likely that my IP is banned (but I tried on multiple machines and all failed with "throttled" error.  Soooo sad < _ <

**Comment by vsakkas** [comment]
Hm, if the "throttled" error persist even after a couple of days have passed, then it might indeed be an IP ban, in which case using a proxy should be a good workaround.

**Comment by wangjk666** [comment]
Ok. Thanks a lot for your kind reply and help. I think this tool is pretty great!

**Comment by Mefisto4444** [comment]
@id@IKDH but what if you use cookies from not logged session? Then after reaching limit from one cookie you should be able reset cookies and reach the limit again

**Comment by Mefisto4444** [comment]
@wangjk666 @vsakkas I am using this tool with cookies from NOT logged session and I have limit of 30 messages without throttling. However if I reset cookies within the same SydneyClient using my functions from above I gain another 30 messages. Repeating this cycle gives me unlimited access to copilot

**Comment by wangjk666** [comment]
https://github.com/vsakkas/sydney.py/issues/133#issuecomment-1858491418 You mean with these two functions you could own unlimited access to copilot? That's weird, I always fail.

**Comment by Mefisto4444** [comment]
Try to copy my approach exactly the same from above and see if that helps

**Comment by wangjk666** [comment]
I tried your code (see https://github.com/vsakkas/sydney.py/issues/133#issuecomment-1858662298) but still fail.

**Comment by Mefisto4444** [comment]
> @wangjk666 @vsakkas I am using this tool with cookies from NOT logged session and I have limit of 30 messages without throttling. However if I reset cookies within the same SydneyClient using my functions from above I gain another 30 messages. Repeating this cycle gives me unlimited access to copilot

Try exactly this approach. Don't change any step.

**Comment by IKDH** [comment]
> @IKDH but what if you use cookies from not logged session? Then after reaching limit from one cookie you should be able reset cookies and reach the limit again

I will try and let you know ! By the way, have you been able to run this on a server like AWS or are you running it on a computer ?

**Comment by Mefisto4444** [comment]
> > @IKDH but what if you use cookies from not logged session? Then after reaching limit from one cookie you should be able reset cookies and reach the limit again
> 
> I will try and let you know ! By the way, have you been able to run this on a server like AWS or are you running it on a computer ?

PC windows 10

**Comment by IKDH** [comment]
@Mefisto4444 it doesn't work with non logged session cookie. I get a captcha error but any captcha appear in the Microsoft Bing Chat UI. So I can't solve it.

**Comment by Mefisto4444** [comment]
@IKDH If you get captcha when trying to get new non logged session cookie then use [curl_cffi](https://github.com/yifeikong/curl_cffi) instead of requests. But if this is sydney problem then there is nothing we can do about this ;(. Maybe the thing with required logged session cookies is country based issue.

**Comment by IKDH** [comment]
I don't know if it isbrelated to my country because I can use Bing chat without being logged in. But with the script, it triggers a captcha. In which country are you ? I will try with a VPN from your country.

**Comment by Mefisto4444** [comment]
Poland

**Comment by IKDH** [comment]
@Mefisto4444 I had made some test. I can generate cookies with your script but when I use them on this librairy, i get this error : Failed to create conversation, received status: 404

**Comment by Mefisto4444** [comment]
Unfortunately after long amount of time my method seems to be ignored by Bing Chat and reseting cookies doesn't help. In my free time I will try to test different request params or maybe entirely change http client for something more stealthy like curl_cffi. I really hope it is not ip based throttling

**Comment by IKDH** [comment]
If it's IP base throttling, you can easely bypass it with a residential rotating proxy like Smartproxy.

What error do you get now ?

**Comment by Mefisto4444** [comment]
sydney.exceptions.ThrottledRequestException: Request is throttled. It's weird because the limit should reset after switching cookies. Sleeping 30 secs changes nothing. I will later try to modify request params or change http client for httpx or curl_cffi

**Comment by IKDH** [comment]
You can try with a residential proxy. It may solve thé problem.

**Comment by Mefisto4444** [comment]
Yes, but with browser you can reset cookies and use it without any limits. I think the goal should be to replicate this but with http requests without proxy. However if nothing will work, using proxy will be the only way

**Comment by IKDH** [comment]
I see. I don't understand why I can use it without being logged in with my computer but not when i try your method, i get a 404 error. I have the same error if I use the librairie without à cooli3.
