### ISSUE TITLE
Is it possible to grab the "block code" automatically?

### ISSUE THREAD

**Issue by RexsyBima** [vsakkas/sydney.py#134]
is it possible to get the value of the block code only? for an exampl, its the json data generated from my prompt
<img width="564" alt="image" src="https://github.com/vsakkas/sydney.py/assets/87449831/1f0836d8-cc53-4c41-9b60-79f35de75eb4">

altho i can do it manually, my prompt is 
``` Python
async def get_newsletter(url):
    async with SydneyClient(style="balanced") as sydney:
        return await sydney.ask("i want your answer to be started ONLY with ""here is the answer : and then ended the final sentence with NOTHING"f". go to this url ONLY {url} and write me a unique newsletter that differs from other sources about it. make sure it retains its accuracy to information. then followed by some formatting, and only formatted in JSON with keys of the title, the newsletter, and the citation.", context=url, raw=True)        
```

and then

``` Python
response = asyncio.run(get_newsletter(url))
data = data.replace("Here is the answer:\n\n```json\n", "").replace("```", "").replace("\n", "")
output = ast.literal_eval(data)
```

unfortunately this workaround is not consistent, sometimes its not working because Bing answer the question in different way

**Comment by vsakkas** [comment]
Hi @RexsyBima 

I don't think the API provides an obvious way to force Bing Chat to output only code, but there a few things that you could try:
- Use `Precise` mode, typically its output is less wordy
- Experiment with different prompts to get a better/more consistent output.
- Improve the parsing of the output. I think that then Bing Chat provides its output, it separates the code using newlines. So if you scan the output line by line, you need to see if you can find two lines that start with the triple ticks. The first one marks the start of the code, the latter marks the end of the code.

The last tip could become a parameter in Sydney it self, but first I will need to check if it's consistent. That being said, I think it's worth trying it as, it should give you better results that using `replace`.

**Comment by RexsyBima** [comment]
ah got it, i think by found the consistent solution by adjusting the prompt to be more straightforward and using precise mode. Thanks!!
