### ISSUE TITLE
KeyError: "text" when running example code

### ISSUE THREAD

**Issue by lixiaochuan2020** [vsakkas/sydney.py#149]
I often encounter this field error when using the sample code.

Can you please tell me what I did wrong? Or is there a place in the code that needs to be updated?

Thank you!
![CleanShot 2024-01-29 at 16 44 29@2x](https://github.com/vsakkas/sydney.py/assets/83334710/d8f52477-4b07-40b7-845b-db5974bb43ee)

![CleanShot 2024-01-29 at 16 43 25@2x](https://github.com/vsakkas/sydney.py/assets/83334710/63255fd7-3184-4454-a2db-1d1265aca832)

**Comment by vsakkas** [comment]
Hi @lixiaochuan2020 

Please have a look at `0.20.2`, it should fix this issue for you. Thanks!

**Comment by lixiaochuan2020** [comment]
Thats cool! Thanks!
