### ISSUE TITLE
Cannot get Cookies from webpage now

### ISSUE THREAD

**Issue by Looong01** [vsakkas/sydney.py#178]
For the newest version of Copilot, there is no request named ```create?bundleVersion=XYZ```.
And for the cookies of requests like, ```create?bundleVersion=1.1788.0``` and ```chats?bundleVersion=1.1788.0```, are useless(cannot connect to the account to pass the CAPTCHA checking).

**Comment by Luneye** [comment]
1. By using this URL, you can find the `create?bundleVersion request` and obtain the cookies from there: https://www.bing.com/chat?q=Microsoft+Copilot&FORM=hpcodx. Alternatively, you can get the cookies from any request like `xls.aspx`.

2. To bypass the CAPTCHA, use this link: https://www.bing.com/turing/captcha/challenge. Once you receive the success message, retrieve your cookies as mentioned in 1.
