### ISSUE TITLE
What am I missing ?

### ISSUE THREAD

**Issue by sirPhoebus** [vsakkas/sydney.py#29]
```
async def main() -> None:
    async with SydneyClient() as sydney:
        response = sydney.ask("When was Bing Chat released?", citations=True)
        print(response)


if __name__ == "__main__":
    asyncio.run(main())
```

gives :
C:\Python310\lib\asyncio\events.py:80: RuntimeWarning: coroutine 'SydneyClient.ask' was never awaited
  self._context.run(self._callback, *self._args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by vsakkas** [comment]
Hi @sirPhoebus , thanks for reaching out!

One mistake that I can see in the example code is that you are not using the `await` keyword on the `ask` method, which is what is triggering the error.

**Comment by vsakkas** [comment]
It appears that some of the examples on the README were also missing the `await` keyword!

https://github.com/vsakkas/sydney.py/pull/30 should fix this.

Thanks for bringing attention to this!

**Comment by sirPhoebus** [comment]
Thanks !! Indeed that fixes everything :))
