### ISSUE TITLE
Page Content for the BingChat?

### ISSUE THREAD

**Issue by tugberkcapraz** [vsakkas/sydney.py#33]
Hi, 
Thank you so much for sharing this package. It's really helpful. 

I know most probably it's not possible but I wanted ask it anyway. You know bing, when permission is granted, can acccess the current page that you are viewing on your browser and you can directly chat about that page. 

As you know, currently we can't provide context to bing chat as it has 2000 characters limit. But when the permission is given, it can get the page content by itself and it's super useful.

For instance, I go to any github repo and start chatting about that repo. And with some proper prompt handling, it provides code reviews as well as providing the code for requested features itself. It's like free GPT4 with super big context window. Also it still searches the web when it thinks necessary :) 

My question is can we mimic this behaviour in this package, for instance, user provides a url inside the python script (as if it's viewing it on the browswer) and bing chat gets the context by itself from the url? 

I hope my question was clear. 

Thanks for reading it  :)

Edit: I thought this feature was only available for the edge developer version, but I checked it now and i see that it's possible to grant permissions in the normal edge browser too.

**Comment by vsakkas** [comment]
Hi @tugberkcapraz

Thanks for the suggestion, this looks like an exciting feature that could make Sydney.py much more useful! As of now, I am not sure yet of how it could be done (if possible). However, I will spend some time to do some investigation on this feature and will follow up later, either with some comments or an MR, depending on how the investigation goes.

**Comment by vsakkas** [comment]
Looks like that this *might* be possible. There are some API calls that are used exactly for this purpose, so I will look into integrating those into the SydneyClient and doing some local testing.

**Comment by vsakkas** [comment]
Took a while, but version `0.17.0` now supports the `context` parameter which can do exactly this!
