### ISSUE TITLE
Suggestions to work around current connection issues (Cloudflare).

### ISSUE THREAD

**Issue by victorchryz** [vsakkas/sydney.py#50]
I have recently been experiencing issues with the library, but I really like its simplicity and wouldn't want to switch to another one. While looking for solutions, I just came across an interesting topic that might be our solution to recent problems. I haven't implemented it yet, but I'm leaving it here for your analysis.

You can find more details in this link: https://github.com/danny-avila/LibreChat/issues/370#issuecomment-1560382302

**Comment by vsakkas** [comment]
Hi, thanks for opening this issue! I had a look at the linked issue, but this is not something that I have encountered before. Also, you can check the latest CI [run](https://github.com/vsakkas/sydney.py/actions/runs/6004384157/job/16284931238) in which all tests passed.

If you're experiencing any issues related to the Captcha challenge, there is a way to fix it. I wrote about it [here](https://github.com/vsakkas/sydney.py/issues/43#issuecomment-1694414503). The solution requires some manual actions, but it worked on my side.

Let me know if you have more questions, or this did not cover the problem you're facing, please provide more details on how to reproduce. Thanks!

**Comment by vsakkas** [comment]
Should be fixed by `0.18.0`
