### ISSUE TITLE
Ability to use without cookies

### ISSUE THREAD

**Issue by Eikosa** [vsakkas/sydney.py#56]
As it is known, it is possible to use bing without logging in, including chrome, other browsers. It would be nice if this feature was added

**Comment by vsakkas** [comment]
That should be easy to implement so that the cookies are optional.

One problem with this is it seems this does not work for my region, which makes it challenging to test. I'll see what I can do.

**Comment by eforce67** [comment]
@Eikosa While it may not be considered a feature, that is already available. If you read the code for class SydneyClient:

> bing_u_cookie: str | None
> The _U cookie from Bing required to connect and use Bing Chat. If not provided,
> the `BING_U_COOKIE` environment variable is loaded instead. Default is None.

That means if **bing_u_cookie** is not provided to the class **SydneyClient** when called, then it will resort to using the environment variable which can be called by importing os and using **os.environ["BING_U_COOKIE"] = 'OPTIONAL'**!

**Comment by vsakkas** [comment]
Hi, please give version `0.17.0`, it should let you use the library without setting the cookie environment avriable
