### ISSUE TITLE
Error! Solve CAPTCHA to continue

### ISSUE THREAD

**Issue by BlackDicky** [vsakkas/sydney.py#57]
`File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sydney/sydney.py", line 233, in _ask
    raise CaptchaChallengeException("Solve CAPTCHA to continue")
sydney.exceptions.CaptchaChallengeException: Solve CAPTCHA to continue` **Unfortunately, I'm encountering this error with the update 0.15.0.** @vsakkas

**Comment by vsakkas** [comment]
Hi @BlackDicky 

Please follow the instructions from here and let me know if it works for you: https://github.com/vsakkas/sydney.py/issues/43#issuecomment-1694414503

**Comment by vsakkas** [comment]
Hi @BlackDicky 

Looks like there were some changes just yesterday on the Bing Chat API. I've updated the code and instructions to reflect that: https://github.com/vsakkas/sydney.py#prerequisites
