### ISSUE TITLE
Still getting a Captcha exception

### ISSUE THREAD

**Issue by regstuff** [vsakkas/sydney.py#76]
Hello,
I've followed the instructions and even entered a new cookie each time (by logging in and out in the browser), but I still get 
`raise CaptchaChallengeException("Solve CAPTCHA to continue")`
Any way around this?

**Comment by vsakkas** [comment]
Hi @regstuff 

Thank you for raising this issue. Unfortunately, it seems that I cannot reproduce this issue on my setup. Before you got the cookies, did you make sure to write a message to Bing Chat on the browser itself? Sometimes, it is necessary to do that before you can actually use the cookies. Also, make sure you're using the cookies from `edgeservices.bing.com`.

**Comment by regstuff** [comment]
Yes I followed the procedure to get the cookie. It is from edgeservices.bing.com and I am taking it after I write a message. 
Tried with a different Edge profile and also on a different laptop. But no luck. This is the code I'm using. Do you see anything wrong here? (Have cut out the cookie details for privacy)
```
import asyncio, os
from sydney import SydneyClient

os.environ["BING_U_COOKIE"] = "1...A"

async def main():
    async with SydneyClient(style="creative") as sydney:
        response = await sydney.ask("When was Bing Chat released?", citations=True)
        print(response)

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by vsakkas** [comment]
Hi @regstuff I tested your code on my laptop and it worked for me. At first I was also receiving the same error, but I got a new Captcha and it fixed the problem.

A few of suggestions:
- Make sure you're using the latest version of Sydney.py
- Make sure you're always using recent cookies and that you have seen the `Success!` message from Bing Chat
- See if you can try to run the code from a different IP. Perhaps you've used Bing Chat several times that might be triggering this error.
- If possible, see if you're getting the same behavior on Linux.
- If you're using some VPN, perhaps try disabling it.

**Comment by regstuff** [comment]
Hi.
Tried all of these, but no luck. :(
Not sure what you mean by the Success! message from Bing Chat.
I take the cookies after sending a message and receiving a reply in the Edge sidebar. Here's a screenshot
![Capture](https://github.com/vsakkas/sydney.py/assets/6016831/4899db9d-9dc3-40a0-bdd7-b291e727222b)

**Comment by IKDH** [comment]
You should 
1. Run your script with a cookie and get a captcha error
2. Go to the bing chat session related to this cookie
3. Send a random message
4. Then you should see the captcha box appear and validate it
5. Run your script again

It works for me.

**Comment by IKDH** [comment]
By the way, @vsakkas, in my region, I am able to discuss with Bing Chat in private navigation (without U cookie) but when I set up the cookie as optional in the script, it raised a captcha. Do you know how to solve that ?

**Comment by vsakkas** [comment]
Hi @IKDH This is something that I am interested in looking at. I am doing some testing using incognito mode to better understand the differences between using the cookie and without.
From a first look, indeed, there are some subtle differences in the request payload, so I will investigate to see if that changes anything.

**Comment by vsakkas** [comment]
Well, it's a bit weird. One of the differences between using cookies and not using cookies is that when you use Bing Chat in incognito, the `sliceIds` field has a bunch of values. But they change every time I open a new browser window and start a conversation... I will focus for now on other parts of the request

**Comment by vsakkas** [comment]
@IKDH I am still looking into this, but lately I am getting throttled quite a lot which makes it hard to test anything. Hopefully, I will be able to come up with an MR for this soon :crossed_fingers:

**Comment by IKDH** [comment]
You are getting throttled in Incognito mode ?

**Comment by vsakkas** [comment]
Not in incognito, but with cookies (which the test suite uses) which I use often to test things

**Comment by IKDH** [comment]
You can easily link 4+ mails to Microsoft Bing. So when one is getting throttled, you can switch to the other. I think you can do 300 requests per day per account.

**Comment by vsakkas** [comment]
That's a good suggestion! I might set up a second account to grab cookies just for the [test suite](https://github.com/vsakkas/sydney.py/actions/runs/6789519552/job/18457123165)
