### ISSUE TITLE
Attachment failure

### ISSUE THREAD

**Issue by ghostbullet** [vsakkas/sydney.py#84]
I use default lib from you get this error:
sydney.exceptions.ImageUploadException: Failed to upload image, received empty image info from Bing Chat
Check it out blobID should be like: {"blobId":"*****************","processedBlobId":"************"} but your response is {"blobId":"","processedBlobId":""}, this cause error.
Then I modify your to make upload local photo to https://www.bing.com/images/kblob, after that I get right value for blobID, processedBlobId. Then that JSON response from /image/kblob it fit with your code (response_dict = await response.json() in sydney.py).

Then I log received messages from wss, this error show up, please check again image upload:
['{"type":2,"invocationId":"0","item":{"firstNewMessageIndex":null,"defaultChatName":null,"conversationId":"51D|BingProdUnAuthenticatedUsers|****************************","requestId":"*****************************","telemetry":{"startTime":"2023-10-24T16:53:12.8064874Z"},"result":{"value":"InternalError","message":"ServiceClient failure for Gptv","error":"ServiceClient failure for Gptv\\n ---> Failed to call \\"Gptv\\" at \\"SelectedByPapyrusLoadBalancer\\". HttpCode= - ResponseCode=Unknown - LoadBalancerResponseCode=SchedulingRejected - AMLModelErrorStatusCode=-1 - ReasonPhrase= - AMLModelErrorReason=.","exception":"Microsoft.TuringBot.Common.ServiceClientException: ServiceClient failure for Gptv\\r\\n ---> System.Net.Http.HttpRequestException: Failed to call \\"Gptv\\" at \\"SelectedByPapyrusLoadBalancer\\". HttpCode= - ResponseCode=Unknown - LoadBalancerResponseCode=SchedulingRejected - AMLModelErrorStatusCode=-1 - ReasonPhrase= - AMLModelErrorReason=.\\r\\n   --- End of inner exception stack trace ---\\r\\n   at BotClientLibrary.ServiceClients.ServiceClient.SendPapyrusRequest(String url, HttpRequestMessage request, TelemetryScope scope, MetricsCollection metrics, CancellationToken cancellationToken, String serviceName, ServiceClientOptions options) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\BotClientLibrary\\\\ServiceClients\\\\ServiceClient.cs:line 764\\r\\n   at BotClientLibrary.ServiceClients.ServiceClient.Run(Conversation conversation, Message message, CancellationToken cancellationToken, BatchRequest batchRequest, ServiceClientOptions options) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\BotClientLibrary\\\\ServiceClients\\\\ServiceClient.cs:line 429\\r\\n   at BotClientLibrary.Extensions.DeepLeoOrchestrator.UpdateConversationWithContentDescriptions(ExtensionRequest request, ExtensionResponse result, Conversation conversation, DeepLeoEngineState engineState, Message message, TuringBotConfiguration config, CancellationToken cancellationToken) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\BotClientLibrary\\\\Extensions\\\\DeepLeoOrchestrator.cs:line 390\\r\\n   at BotClientLibrary.Extensions.DeepLeoOrchestrator.Run(ExtensionRequest request, CancellationToken cancellationToken) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\BotClientLibrary\\\\Extensions\\\\DeepLeoOrchestrator.cs:line 301\\r\\n   at BotClientLibrary.Extensions.ExtensionRunner.RunExtension(ExtensionRequest request, Conversation conversation, ExtensionConfig extension, ExtensionRequestOptions customOptions, ParsedToolInvocation action, String modelName, CancellationToken cancellationToken) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\BotClientLibrary\\\\Extensions\\\\ExtensionRunner.cs:line 694\\r\\n   at BotClientLibrary.Extensions.ExtensionRunner.RunExtensions(Conversation conversation, CancellationToken cancellationToken, ComponentPriority minPriority, ComponentPriority maxPriority, ExtensionRequestOptions customOptions, ExtensionRequest request, ParsedToolInvocation action, String modelName, Classification modelClassification) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\BotClientLibrary\\\\Extensions\\\\ExtensionRunner.cs:line 291\\r\\n   at BotClientLibrary.BotConnection.GetContentResponsesAsync(Conversation conversation, CancellationToken cancellationToken) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\BotClientLibrary\\\\BotConnection.cs:line 703\\r\\n   at BotClientLibrary.BotConnection.InternalRun(Conversation conversation, CancellationToken cancellationToken) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\BotClientLibrary\\\\BotConnection.cs:line 795\\r\\n   at BotClientLibrary.BotConnection.ExecuteBotTurn(Conversation conversation, CancellationToken cancellationToken) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\BotClientLibrary\\\\BotConnection.cs:line 418\\r\\n   at BotClientLibrary.BotConnection.ExecuteBotTurn(Conversation conversation, CancellationToken cancellationToken) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\BotClientLibrary\\\\BotConnection.cs:line 418\\r\\n   at BotClientLibrary.BotConnection.Run(CancellationToken cancellationToken) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\BotClientLibrary\\\\BotConnection.cs:line 141\\r\\n   at Microsoft.Falcon.TuringBot.ChatApiImplementation.Run(BaseRequest request, BaseResponse response, CancellationToken cancellationToken) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\Service\\\\Implementation\\\\ApiImplementation\\\\ChatApiImplementation.cs:line 164\\r\\n   at Microsoft.Falcon.TuringBot.RequestProcessor.Run(BaseRequest request, BaseResponse response, IRequestContextInitializer contextInitializer, IRequestValidator requestValidator, IApiImplementation apiImplementation, IAsyncApiEndStep apiEndStep, String apiName, CancellationToken cancellationToken, Func`1 cancellationTokenProvider) in C:\\\\a\\\\_work\\\\1\\\\s\\\\services\\\\TuringBot\\\\src\\\\Service\\\\Implementation\\\\RequestProcessor.cs:line 260","serviceVersion":"20231023.32"}}}', '{"type":3,"invocationId":"0"}', '']

**Comment by vsakkas** [comment]
Hi @ghostbullet Please update to version `0.17.0`, it should fix your issue with the attachment
