### ISSUE TITLE
Word or character missing

### ISSUE THREAD

**Issue by IKDH** [vsakkas/sydney.py#88]
Sometimes, when I use the function ask_stream, the first character or the first word of the response is missing.

async for response in syd.ask_stream(prompt):
                            res.append(response)

**Comment by vsakkas** [comment]
Hi @IKDH Can you try `0.17.2` and let me know if that fixes the issue for you? Thanks!

**Comment by IKDH** [comment]
It definitively have solved it. Thanks !
