### ISSUE TITLE
Is it possible that the creative, balanced and precise parameter is not working ?

### ISSUE THREAD

**Issue by IKDH** [vsakkas/sydney.py#91]
When I use the librairie, the quality of the content is not the same as when I use Bing Chat. I have performed a test I have used the Balanced mode. In this mode the max number of character is 2000. I have given a prompt with arround 3500 characters and I have received an answer as if all the character have been read by Bing. So I assume that it was not in Balanced mode, otherwise, it shouldn't have read all my prompt.

Thank you.

**Comment by vsakkas** [comment]
Hi @IKDH
Thank you for raising this issue, it's worth investigating it to see if something has changed in the API perhaps. Are you using the library with or without cookies?

**Comment by IKDH** [comment]
Hello, I am using it with cookies.

**Comment by vsakkas** [comment]
Thanks, will update this issue if I find something!

**Comment by IKDH** [comment]
@vsakkas if this can help you, I have tried the v0.15.2 and the quality is way better in creative mode. It's the same quality as when I directly ask Bing Chat with the Microsoft UI. Maybe something went wrong between v15 and v16.

**Comment by vsakkas** [comment]
@IKDH This is useful to know. I checked that there's definitely a few differences between the request payload that Sydney sends compared to what happens on the browser. I will try later today to push a change to make it more consistent.

**Comment by IKDH** [comment]
> @IKDH This is useful to know. I checked that there's definitely a few differences between the request payload that Sydney sends compared to what happens on the browser. I will try later today to push a change to make it more consistent.

I have done lot of test with the creative mode of the v15 and it's actually very good. The creative mode of the v16 and plus seem to be more like a precise or a balanced mode. I don't think the problem come from recent change of Bing Chat API but more of a change between v15 and v16.

**Comment by arismoko** [comment]
Experiencing the same thing. This was the question I asked: I have 4 apples today. I ate 3 apples yesterday. How many apples do I have today?

`Creative mode - You have 1 apple today.`

`Balance mode - You have 1 apple today.`

`Precise mode - You have 1 apple today.`

```
Creative mode (website) - Hello, this is Bing. I can help you with simple math problems. 😊
To find out how many apples you have today, you need to subtract the number of apples you ate yesterday from the number of apples you had today. The formula is: apples today=apples yesterday−apples eaten Plugging in the numbers, we get: apples today=4−3 Simplifying, we get: apples today=1 Therefore, you have one apple today. 🍎
```

`Balance mode (website) - You have 1 apple today.`

`Precise mode (website) - You still have 4 apples today. The apples you ate yesterday don’t affect the number of apples you have today.`

**Comment by vsakkas** [comment]
Hm, there are two possible things that could have caused this change in v0.16:
- Image uploading which resulted in some small changes in the payload of the requests, but I have a PR for this, once I stop getting throttled, I will merge and release it.
- Reusing the session object across requests. This might actually be the cause, so I will look into reversing this change as well.

**Comment by vsakkas** [comment]
Ok, so I tried the apple question using `0.17.3` and these are the results:

 **Creative**

This is a simple arithmetic problem. You can solve it by subtracting the number of apples you ate yesterday from the number of apples you have today. The formula is:

$$\text{Number of apples today} = \text{Number of apples yesterday} - \text{Number of apples eaten}$$

In your case, the number of apples today is 4, the number of apples yesterday is 4, and the number of apples eaten is 3. So, the solution is:

$$\text{Number of apples today} = 4 - 3$$

$$\text{Number of apples today} = 1$$

Therefore, you have **one apple** today. 🍎

I hope this helps you understand how to solve this kind of problem. 😊

 **Balanced**

You have **1 apple** today. You started with 4 apples, and you ate 3 apples yesterday, so you have 1 apple left .

 **Creative**

You have **4 apples** today. The apples you ate yesterday don't affect the number of apples you have today. So, you still have **4 apples**. Enjoy your apples! 🍎

**Comment by IKDH** [comment]
I will try the v17.3 and tell you !

**Comment by IKDH** [comment]
It is working fine with this new version !

**Comment by vsakkas** [comment]
Amazing!
