### ISSUE TITLE
Error : index out of range

### ISSUE THREAD

**Issue by IKDH** [vsakkas/sydney.py#97]
Hello, since few hours, I have a lot of errors : index out of range. Sometimes it comes on the first prompt and sometimes after few prompts on the same chat.

I am wondering if it's not triggered by a bad internet connection because when I use the UI of Bing Chat, I can see that the chat is trying to reconnect.

**Comment by vsakkas** [comment]
Hm, I haven't been able to reproduce this issue, although I did get a few timeout errors and saw the Bing Chat UI try to reconnect a few times.
I will look into it a bit more.

**Comment by IKDH** [comment]
Even with many prompts in the same chat you don't have this issue ?

**Comment by vsakkas** [comment]
I'll try again. Does this occur with `ask` or `ask_stream` (or both) for you?

**Comment by IKDH** [comment]
It occurs with ask_stream.

**Comment by vsakkas** [comment]
Got it, I was trying with `ask`, so maybe that's why. I'll try with stream and I'll see if I can reproduce.

**Comment by IKDH** [comment]
I will change my code to use "ask" to see how it behaves.

**Comment by vsakkas** [comment]
Hm, I also tried something like this:

```python

**Comment by vsakkas** [comment]
I also tried something like this:

```python
    async with SydneyClient(style="balanced") as sydney:
        async for response in sydney.ask_stream("Tell me a joke"):
            print(response, end="", flush=True)

        async for response in sydney.ask_stream("Tell me another one"):
            print(response, end="", flush=True)

        async for response in sydney.ask_stream("Tell me one more"):
            print(response, end="", flush=True)

        async for response in sydney.ask_stream("Another one, please"):
            print(response, end="", flush=True)

        async for response in sydney.ask_stream("One more joke, please?"):
            print(response, end="", flush=True)
 ```
 
 But still no index error :/
 Do you have any tracebacks to provide? Could help see the exact line that gave the index error.

**Comment by IKDH** [comment]
It's seem to be working now...
I had this error all day but it's seems to be fine now.

**Comment by vsakkas** [comment]
Hm, maybe it was some server side hiccup in the region that serves you?
I haven't been able to reproduce this, so for now I will close this issue, but feel free to re-open if this error comes up again.

**Comment by IKDH** [comment]
Of course. Thank you !
